name: cDisguise
main: dev.brighten.hide.Disguise
description: Designed to anonymize players. Developed for Smok Network.
version: ${project.version}
softdepend: [AquaCore]
depend: [Atlas, Vault]
author: funkemunky